// Code generated by protoc-gen-go. DO NOT EDIT.
// source: candidature.proto

package candidature

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Candidature struct {
	Legislatura           int64      `protobuf:"varint,1,opt,name=Legislatura,proto3" json:"Legislatura,omitempty"`
	Cargo                 int64      `protobuf:"varint,2,opt,name=Cargo,proto3" json:"Cargo,omitempty"`
	UF                    string     `protobuf:"bytes,3,opt,name=UF,proto3" json:"UF,omitempty"`
	Municipio             string     `protobuf:"bytes,4,opt,name=Municipio,proto3" json:"Municipio,omitempty"`
	NumeroUrna            int64      `protobuf:"varint,5,opt,name=NumeroUrna,proto3" json:"NumeroUrna,omitempty"`
	NomeUrna              string     `protobuf:"bytes,6,opt,name=NomeUrna,proto3" json:"NomeUrna,omitempty"`
	Aptdao                string     `protobuf:"bytes,7,opt,name=Aptdao,proto3" json:"Aptdao,omitempty"`
	Deferimento           string     `protobuf:"bytes,8,opt,name=Deferimento,proto3" json:"Deferimento,omitempty"`
	TipoAgremiacao        string     `protobuf:"bytes,9,opt,name=TipoAgremiacao,proto3" json:"TipoAgremiacao,omitempty"`
	NumeroPartido         int64      `protobuf:"varint,10,opt,name=NumeroPartido,proto3" json:"NumeroPartido,omitempty"`
	LegendaPartido        string     `protobuf:"bytes,11,opt,name=LegendaPartido,proto3" json:"LegendaPartido,omitempty"`
	NomePartido           string     `protobuf:"bytes,12,opt,name=NomePartido,proto3" json:"NomePartido,omitempty"`
	NomeColigacao         string     `protobuf:"bytes,13,opt,name=NomeColigacao,proto3" json:"NomeColigacao,omitempty"`
	PartidosColigacao     string     `protobuf:"bytes,14,opt,name=PartidosColigacao,proto3" json:"PartidosColigacao,omitempty"`
	DeclarouBens          bool       `protobuf:"varint,15,opt,name=DeclarouBens,proto3" json:"DeclarouBens,omitempty"`
	SituacaoPrimeiroTurno string     `protobuf:"bytes,16,opt,name=SituacaoPrimeiroTurno,proto3" json:"SituacaoPrimeiroTurno,omitempty"`
	SituacaoSegundoTurno  string     `protobuf:"bytes,17,opt,name=SituacaoSegundoTurno,proto3" json:"SituacaoSegundoTurno,omitempty"`
	SequencialCandidato   string     `protobuf:"bytes,18,opt,name=SequencialCandidato,proto3" json:"SequencialCandidato,omitempty"`
	Candidato             *Candidato `protobuf:"bytes,19,opt,name=candidato,proto3" json:"candidato,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *Candidature) Reset()         { *m = Candidature{} }
func (m *Candidature) String() string { return proto.CompactTextString(m) }
func (*Candidature) ProtoMessage()    {}
func (*Candidature) Descriptor() ([]byte, []int) {
	return fileDescriptor_892ddf6c243ffcc2, []int{0}
}

func (m *Candidature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidature.Unmarshal(m, b)
}
func (m *Candidature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidature.Marshal(b, m, deterministic)
}
func (m *Candidature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidature.Merge(m, src)
}
func (m *Candidature) XXX_Size() int {
	return xxx_messageInfo_Candidature.Size(m)
}
func (m *Candidature) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidature.DiscardUnknown(m)
}

var xxx_messageInfo_Candidature proto.InternalMessageInfo

func (m *Candidature) GetLegislatura() int64 {
	if m != nil {
		return m.Legislatura
	}
	return 0
}

func (m *Candidature) GetCargo() int64 {
	if m != nil {
		return m.Cargo
	}
	return 0
}

func (m *Candidature) GetUF() string {
	if m != nil {
		return m.UF
	}
	return ""
}

func (m *Candidature) GetMunicipio() string {
	if m != nil {
		return m.Municipio
	}
	return ""
}

func (m *Candidature) GetNumeroUrna() int64 {
	if m != nil {
		return m.NumeroUrna
	}
	return 0
}

func (m *Candidature) GetNomeUrna() string {
	if m != nil {
		return m.NomeUrna
	}
	return ""
}

func (m *Candidature) GetAptdao() string {
	if m != nil {
		return m.Aptdao
	}
	return ""
}

func (m *Candidature) GetDeferimento() string {
	if m != nil {
		return m.Deferimento
	}
	return ""
}

func (m *Candidature) GetTipoAgremiacao() string {
	if m != nil {
		return m.TipoAgremiacao
	}
	return ""
}

func (m *Candidature) GetNumeroPartido() int64 {
	if m != nil {
		return m.NumeroPartido
	}
	return 0
}

func (m *Candidature) GetLegendaPartido() string {
	if m != nil {
		return m.LegendaPartido
	}
	return ""
}

func (m *Candidature) GetNomePartido() string {
	if m != nil {
		return m.NomePartido
	}
	return ""
}

func (m *Candidature) GetNomeColigacao() string {
	if m != nil {
		return m.NomeColigacao
	}
	return ""
}

func (m *Candidature) GetPartidosColigacao() string {
	if m != nil {
		return m.PartidosColigacao
	}
	return ""
}

func (m *Candidature) GetDeclarouBens() bool {
	if m != nil {
		return m.DeclarouBens
	}
	return false
}

func (m *Candidature) GetSituacaoPrimeiroTurno() string {
	if m != nil {
		return m.SituacaoPrimeiroTurno
	}
	return ""
}

func (m *Candidature) GetSituacaoSegundoTurno() string {
	if m != nil {
		return m.SituacaoSegundoTurno
	}
	return ""
}

func (m *Candidature) GetSequencialCandidato() string {
	if m != nil {
		return m.SequencialCandidato
	}
	return ""
}

func (m *Candidature) GetCandidato() *Candidato {
	if m != nil {
		return m.Candidato
	}
	return nil
}

type Candidato struct {
	UF                   string               `protobuf:"bytes,1,opt,name=UF,proto3" json:"UF,omitempty"`
	Municipio            string               `protobuf:"bytes,2,opt,name=Municipio,proto3" json:"Municipio,omitempty"`
	Nascimento           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Nascimento,proto3" json:"Nascimento,omitempty"`
	TituloEleitoral      string               `protobuf:"bytes,4,opt,name=TituloEleitoral,proto3" json:"TituloEleitoral,omitempty"`
	Genero               string               `protobuf:"bytes,5,opt,name=Genero,proto3" json:"Genero,omitempty"`
	GrauInstrucao        string               `protobuf:"bytes,6,opt,name=GrauInstrucao,proto3" json:"GrauInstrucao,omitempty"`
	EstadoCivil          string               `protobuf:"bytes,7,opt,name=EstadoCivil,proto3" json:"EstadoCivil,omitempty"`
	Raca                 string               `protobuf:"bytes,8,opt,name=Raca,proto3" json:"Raca,omitempty"`
	Ocupacao             string               `protobuf:"bytes,9,opt,name=Ocupacao,proto3" json:"Ocupacao,omitempty"`
	CPF                  string               `protobuf:"bytes,10,opt,name=CPF,proto3" json:"CPF,omitempty"`
	Nome                 string               `protobuf:"bytes,11,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Email                string               `protobuf:"bytes,12,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Candidato) Reset()         { *m = Candidato{} }
func (m *Candidato) String() string { return proto.CompactTextString(m) }
func (*Candidato) ProtoMessage()    {}
func (*Candidato) Descriptor() ([]byte, []int) {
	return fileDescriptor_892ddf6c243ffcc2, []int{1}
}

func (m *Candidato) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidato.Unmarshal(m, b)
}
func (m *Candidato) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidato.Marshal(b, m, deterministic)
}
func (m *Candidato) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidato.Merge(m, src)
}
func (m *Candidato) XXX_Size() int {
	return xxx_messageInfo_Candidato.Size(m)
}
func (m *Candidato) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidato.DiscardUnknown(m)
}

var xxx_messageInfo_Candidato proto.InternalMessageInfo

func (m *Candidato) GetUF() string {
	if m != nil {
		return m.UF
	}
	return ""
}

func (m *Candidato) GetMunicipio() string {
	if m != nil {
		return m.Municipio
	}
	return ""
}

func (m *Candidato) GetNascimento() *timestamp.Timestamp {
	if m != nil {
		return m.Nascimento
	}
	return nil
}

func (m *Candidato) GetTituloEleitoral() string {
	if m != nil {
		return m.TituloEleitoral
	}
	return ""
}

func (m *Candidato) GetGenero() string {
	if m != nil {
		return m.Genero
	}
	return ""
}

func (m *Candidato) GetGrauInstrucao() string {
	if m != nil {
		return m.GrauInstrucao
	}
	return ""
}

func (m *Candidato) GetEstadoCivil() string {
	if m != nil {
		return m.EstadoCivil
	}
	return ""
}

func (m *Candidato) GetRaca() string {
	if m != nil {
		return m.Raca
	}
	return ""
}

func (m *Candidato) GetOcupacao() string {
	if m != nil {
		return m.Ocupacao
	}
	return ""
}

func (m *Candidato) GetCPF() string {
	if m != nil {
		return m.CPF
	}
	return ""
}

func (m *Candidato) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Candidato) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ProcessedCandidature struct {
	Group                map[string]*Candidature `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProcessedCandidature) Reset()         { *m = ProcessedCandidature{} }
func (m *ProcessedCandidature) String() string { return proto.CompactTextString(m) }
func (*ProcessedCandidature) ProtoMessage()    {}
func (*ProcessedCandidature) Descriptor() ([]byte, []int) {
	return fileDescriptor_892ddf6c243ffcc2, []int{2}
}

func (m *ProcessedCandidature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessedCandidature.Unmarshal(m, b)
}
func (m *ProcessedCandidature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessedCandidature.Marshal(b, m, deterministic)
}
func (m *ProcessedCandidature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessedCandidature.Merge(m, src)
}
func (m *ProcessedCandidature) XXX_Size() int {
	return xxx_messageInfo_ProcessedCandidature.Size(m)
}
func (m *ProcessedCandidature) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessedCandidature.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessedCandidature proto.InternalMessageInfo

func (m *ProcessedCandidature) GetGroup() map[string]*Candidature {
	if m != nil {
		return m.Group
	}
	return nil
}

func init() {
	proto.RegisterType((*Candidature)(nil), "candidature.Candidature")
	proto.RegisterType((*Candidato)(nil), "candidature.Candidato")
	proto.RegisterType((*ProcessedCandidature)(nil), "candidature.ProcessedCandidature")
	proto.RegisterMapType((map[string]*Candidature)(nil), "candidature.ProcessedCandidature.GroupEntry")
}

func init() { proto.RegisterFile("candidature.proto", fileDescriptor_892ddf6c243ffcc2) }

var fileDescriptor_892ddf6c243ffcc2 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x5f, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0xe5, 0x84, 0x50, 0x32, 0xe6, 0xef, 0x42, 0xd1, 0x2a, 0xaa, 0xda, 0x28, 0xaa, 0xaa,
	0x3c, 0x20, 0x53, 0xa5, 0x3c, 0x54, 0xbc, 0x41, 0x08, 0xa8, 0x12, 0xa5, 0x91, 0x09, 0x07, 0x58,
	0xec, 0xc1, 0x5a, 0xd5, 0xf6, 0xb8, 0xeb, 0x5d, 0x24, 0x2e, 0xd5, 0x8b, 0xf4, 0x28, 0xbd, 0x44,
	0xb5, 0x6b, 0x27, 0x71, 0x68, 0xde, 0x76, 0xbe, 0xf9, 0x66, 0x3c, 0xca, 0xfc, 0x26, 0x70, 0x10,
	0x89, 0x3c, 0x96, 0xb1, 0xd0, 0x46, 0x61, 0x50, 0x28, 0xd2, 0xc4, 0xfc, 0x86, 0xd4, 0xfb, 0x90,
	0x10, 0x25, 0x29, 0x9e, 0xba, 0xd4, 0xa3, 0x79, 0x3a, 0xd5, 0x32, 0xc3, 0x52, 0x8b, 0xac, 0xa8,
	0xdc, 0x83, 0x3f, 0x1d, 0xf0, 0xc7, 0xcb, 0x02, 0xd6, 0x07, 0xff, 0x16, 0x13, 0x59, 0xa6, 0x36,
	0x14, 0xdc, 0xeb, 0x7b, 0xc3, 0x76, 0xd8, 0x94, 0xd8, 0x11, 0x74, 0xc6, 0x42, 0x25, 0xc4, 0x5b,
	0x2e, 0x57, 0x05, 0x6c, 0x17, 0x5a, 0x0f, 0xd7, 0xbc, 0xdd, 0xf7, 0x86, 0xdd, 0xb0, 0xf5, 0x70,
	0xcd, 0xde, 0x41, 0xf7, 0xbb, 0xc9, 0x65, 0x24, 0x0b, 0x49, 0x7c, 0xc3, 0xc9, 0x4b, 0x81, 0xbd,
	0x07, 0xb8, 0x33, 0x19, 0x2a, 0x7a, 0x50, 0xb9, 0xe0, 0x1d, 0xd7, 0xa8, 0xa1, 0xb0, 0x1e, 0x6c,
	0xdd, 0x51, 0x86, 0x2e, 0xbb, 0xe9, 0x8a, 0x17, 0x31, 0x3b, 0x86, 0xcd, 0x8b, 0x42, 0xc7, 0x82,
	0xf8, 0x1b, 0x97, 0xa9, 0x23, 0x3b, 0xf9, 0x15, 0x3e, 0xa1, 0x92, 0x19, 0xe6, 0x9a, 0xf8, 0x96,
	0x4b, 0x36, 0x25, 0xf6, 0x09, 0x76, 0x67, 0xb2, 0xa0, 0x8b, 0x44, 0x61, 0x26, 0x45, 0x24, 0x88,
	0x77, 0x9d, 0xe9, 0x95, 0xca, 0x3e, 0xc2, 0x4e, 0x35, 0xcb, 0x54, 0x28, 0x2d, 0x63, 0xe2, 0xe0,
	0x06, 0x5c, 0x15, 0x6d, 0xb7, 0x5b, 0x4c, 0x30, 0x8f, 0xc5, 0xdc, 0xe6, 0x57, 0xdd, 0x56, 0x55,
	0x3b, 0x97, 0x9d, 0x7d, 0x6e, 0xda, 0xae, 0xe6, 0x6a, 0x48, 0xee, 0x7b, 0x94, 0xe1, 0x98, 0x52,
	0x99, 0xb8, 0xb1, 0x76, 0x9c, 0x67, 0x55, 0x64, 0x27, 0x70, 0x50, 0x17, 0x94, 0x4b, 0xe7, 0xae,
	0x73, 0xfe, 0x9f, 0x60, 0x03, 0xd8, 0xbe, 0xc2, 0x28, 0x15, 0x8a, 0xcc, 0x25, 0xe6, 0x25, 0xdf,
	0xeb, 0x7b, 0xc3, 0xad, 0x70, 0x45, 0x63, 0x67, 0xf0, 0xf6, 0x5e, 0x6a, 0x63, 0xfd, 0x53, 0xfb,
	0x1b, 0x49, 0x45, 0x33, 0xa3, 0x72, 0xe2, 0xfb, 0xae, 0xeb, 0xfa, 0x24, 0x1b, 0xc1, 0xd1, 0x3c,
	0x71, 0x8f, 0x89, 0xc9, 0xe3, 0xba, 0xe8, 0xc0, 0x15, 0xad, 0xcd, 0xb1, 0xcf, 0x70, 0x78, 0x8f,
	0xbf, 0x0c, 0xe6, 0x91, 0x14, 0xe9, 0x1c, 0x37, 0xe2, 0xcc, 0x95, 0xac, 0x4b, 0xb1, 0x33, 0xe8,
	0x46, 0x0b, 0xdf, 0x61, 0xdf, 0x1b, 0xfa, 0xa3, 0xe3, 0xa0, 0x09, 0xfb, 0xc2, 0x1a, 0x2e, 0x8d,
	0x83, 0xbf, 0x2d, 0xe8, 0x2e, 0x7b, 0x54, 0x4c, 0x7a, 0xeb, 0x99, 0x6c, 0xbd, 0x66, 0xf2, 0x1c,
	0xe0, 0x4e, 0x94, 0x51, 0x8d, 0x4f, 0xdb, 0x7d, 0xb2, 0x17, 0x54, 0xf7, 0x13, 0xcc, 0xef, 0x27,
	0x98, 0xcd, 0xef, 0x27, 0x6c, 0xb8, 0xd9, 0x10, 0xf6, 0x66, 0x52, 0x9b, 0x94, 0x26, 0x29, 0x4a,
	0x4d, 0x4a, 0xa4, 0x35, 0xf3, 0xaf, 0x65, 0x4b, 0xef, 0x0d, 0xe6, 0xa8, 0xc8, 0x51, 0xdf, 0x0d,
	0xeb, 0xc8, 0x32, 0x70, 0xa3, 0x84, 0xf9, 0x96, 0x97, 0x5a, 0x19, 0xbb, 0xd9, 0x0a, 0xfb, 0x55,
	0xd1, 0xb2, 0x34, 0x29, 0xb5, 0x88, 0x69, 0x2c, 0x9f, 0x65, 0x5a, 0x1f, 0x40, 0x53, 0x62, 0x0c,
	0x36, 0x42, 0x11, 0x89, 0x1a, 0x7f, 0xf7, 0xb6, 0xd7, 0xf4, 0x23, 0x32, 0x45, 0x83, 0xf8, 0x45,
	0xcc, 0xf6, 0xa1, 0x3d, 0x9e, 0x5e, 0x3b, 0xc2, 0xbb, 0xa1, 0x7d, 0xda, 0x0e, 0x16, 0xbc, 0x9a,
	0x66, 0xf7, 0xb6, 0x37, 0x3f, 0xc9, 0x84, 0x4c, 0x6b, 0x7a, 0xab, 0x60, 0xf0, 0xdb, 0x83, 0xa3,
	0xa9, 0xa2, 0x08, 0xcb, 0x12, 0xe3, 0xe6, 0x9f, 0xc8, 0x25, 0x74, 0x12, 0x45, 0xa6, 0xe0, 0x5e,
	0xbf, 0x3d, 0xf4, 0x47, 0x27, 0x2b, 0x8b, 0x5b, 0x57, 0x11, 0xdc, 0x58, 0xfb, 0x24, 0xd7, 0xea,
	0x25, 0xac, 0x4a, 0x7b, 0x21, 0xc0, 0x52, 0xb4, 0x63, 0xfe, 0xc4, 0x97, 0x7a, 0x97, 0xf6, 0xc9,
	0x02, 0xe8, 0x3c, 0x8b, 0xd4, 0xa0, 0x5b, 0xa4, 0x3f, 0xe2, 0x6b, 0xe1, 0x30, 0x0a, 0xc3, 0xca,
	0x76, 0xde, 0xfa, 0xea, 0x3d, 0x6e, 0xba, 0x35, 0x7e, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0xc2, 0xee, 0x5f, 0x36, 0x05, 0x00, 0x00,
}
